### ISSUE TITLE
Warp problems after importing from version prior MyWarp 3

### ISSUE THREAD

**Issue by Bobobaal** [MyWarp/MyWarp#173]
Hello

We updated our server to 1.12.2 and updated from version 2.6.5 to MyWarp 3 dev build 179.
After we updated we change the storage settings, created our schema and imported our old warps using the import command specific for prior MyWarp 3.
But after the import and a restart of the server, players were unable to see their private warps or teleport to their private warps, they also can't private their public warps prior MyWarp 3.

Sincerely

Bobobaal

**Comment by TheE** [comment]
Were there any errors logged in the console during and after the import?

**Comment by Bobobaal** [comment]
During the import there were warps ignored because they lacked an unique ID.
And when you want to look info up about a warp you get an error: https://pastebin.com/GVzd2Qcq

**Comment by TheE** [comment]
Yeiks. This should be fixed by the latest devBuild.

**Comment by Bobobaal** [comment]
The problems we had from after the import are still present.
This is the error you get when you try to make a warp private/public if it's one that we imported from a database prior to MyWarp 3. As stated we used /warp import pre3-mysql

**Comment by Bobobaal** [comment]
Forgot to paste the link of the error: https://vgy.me/8ctCn5.png

**Comment by Bobobaal** [comment]
Also like earlier mentioned, people lost warps because they lacked an unique ID and were not imported

**Comment by TheE** [comment]
This might be a general problem that is caused by the change to unique IDs.

After Mojang allowed players to change their name, players can no longer be identified by name, but by a unique ID. This unique ID is provided by Mojang upon login, and the ID of a name can be queried from Mojang's server as long as (1) the name is used by a player and (2) this player actually brought Minecraft.

MyWarp 2 still stores users by name. MyWarp uses unique IDs instead; when importing data from MyWarp 2, it gets all names and asks Mojang for the unique IDs that correspond to these names. Players may be ignored at this step for two reasons:

1. A player might have changed his name in the meantime, so Mojang cannot return a valid unique ID for him (or returns the ID of a different player who has taken the original name),
2. A player might not have bought Minecraft, so Mojang does not return a unique ID.

The problems you are encountering may be a combination of both: Warps of players without ID are not imported, and if the name was changed, the ID of a different player is imported. In both cases MyWarp will not work as desired.

Unfortunately since the conversion of names to unique IDs relies on the options Mojang provides us with, there is no way to do things differently.

**Comment by Bobobaal** [comment]
During import can't you first check if the server is in online mode or not? And if it's false you convert it to an md5 hash of OfflinePlayer:PLAYERNAME.

**Comment by TheE** [comment]
This would not work, as MyWarp relies on Mojang to lookup the unique IDs of players at several places. Supporting offline servers would require me to implement a different way of doing these lookups which cannot be done easily, because there is no standard way how unique IDs are handled on offline servers. (Missing API in Bukit...)

Besides, honestly I do not want to support players who have not legally bought Minecraft. Sorry.
